# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-06-13 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20180612_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hashtag',
            field=models.ManyToManyField(to='feed.Hashtag'),
        ),
    ]
