# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-06-14 05:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_article_hashtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('dv', 'development'), ('ps', 'personal'), ('gr', 'gallery')], default='dv', max_length=2),
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_comments', to='feed.Article'),
        ),
    ]
