# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-06-14 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_auto_20180614_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='sub',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
